// Drizzle schema — Phase 2
// Tables: products, product_options, quantity_tiers, orders, order_items, order_files
//
// Conventions:
//   - All monetary values are in cents (integer) — no floats.
//   - Timestamps are timestamptz stored as JS Date objects.
//   - UUIDs are generated by Postgres (gen_random_uuid()).
//   - Order status is plain text + check constraint (not a PG enum) so adding
//     a new status value never requires a migration.

import {
  pgTable,
  uuid,
  text,
  integer,
  boolean,
  jsonb,
  timestamp,
  uniqueIndex,
  index,
  check,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" })
    .notNull()
    .defaultNow(),
};

// ---------------------------------------------------------------------------
// products
// ---------------------------------------------------------------------------

export const products = pgTable("products", {
  id: uuid("id").primaryKey().defaultRandom(),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  description: text("description"),
  category: text("category").notNull(),
  basePrice: integer("base_price").notNull(), // cents
  active: boolean("active").notNull().default(true),
  // Drives Quick Preview feature — never hardcode eligible slugs in code.
  quickPreviewEnabled: boolean("quick_preview_enabled").notNull().default(false),
  ...timestamps,
});

// ---------------------------------------------------------------------------
// product_options
//
// One row per selectable option value (not per option group).
// group_name is the logical grouping key: "size", "finish", "material", etc.
// Unique per (product_id, group_name, value) — no duplicate values within a group.
// ---------------------------------------------------------------------------

export const productOptions = pgTable(
  "product_options",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    productId: uuid("product_id")
      .notNull()
      .references(() => products.id, { onDelete: "cascade" }),
    groupName: text("group_name").notNull(),
    label: text("label").notNull(),
    value: text("value").notNull(),
    priceModifier: integer("price_modifier").notNull().default(0), // cents delta
    sortOrder: integer("sort_order").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("product_options_product_group_value_idx").on(
      t.productId,
      t.groupName,
      t.value
    ),
  ]
);

// ---------------------------------------------------------------------------
// quantity_tiers
//
// Each tier: buy at least min_qty units → pay unit_price cents each.
// Highest qualifying tier (largest min_qty ≤ selected qty) wins.
// See lib/pricing.ts for resolution logic.
// ---------------------------------------------------------------------------

export const quantityTiers = pgTable(
  "quantity_tiers",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    productId: uuid("product_id")
      .notNull()
      .references(() => products.id, { onDelete: "cascade" }),
    minQty: integer("min_qty").notNull(),
    unitPrice: integer("unit_price").notNull(), // cents per unit at this tier
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("quantity_tiers_product_min_qty_idx").on(
      t.productId,
      t.minQty
    ),
  ]
);

// ---------------------------------------------------------------------------
// orders
//
// No user_id FK yet — Supabase auth is Phase 4.
// customer_email is the placeholder link to future accounts.
//
// status values (check constraint keeps them without a PG enum):
//   pending → paid → artwork_review → proof_sent → proof_approved
//   → in_production → shipped → complete
//   + terminal: payment_failed, cancelled
// ---------------------------------------------------------------------------

export const ORDER_STATUSES = [
  "pending",
  "paid",
  "artwork_review",
  "proof_sent",
  "proof_approved",
  "in_production",
  "submitted_to_vendor",
  "fulfillment_failed",
  "shipped",
  "complete",
  "payment_failed",
  "cancelled",
] as const;

export type OrderStatus = (typeof ORDER_STATUSES)[number];

export const orders = pgTable(
  "orders",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    customerEmail: text("customer_email").notNull(),
    customerName: text("customer_name").notNull(),
    status: text("status")
      .notNull()
      .default("pending")
      .$type<OrderStatus>(),
    stripeSessionId: text("stripe_session_id"),
    stripePaymentIntent: text("stripe_payment_intent"),
    subtotalCents: integer("subtotal_cents").notNull(), // sum of line totals before any fees/tax
    totalCents: integer("total_cents").notNull(),       // final charged amount
    shippingAddress: jsonb("shipping_address").$type<{
      line1: string;
      line2?: string;
      city: string;
      state: string;
      postalCode: string;
      country: string;
    }>(),
    fulfillmentRecommendation: jsonb("fulfillment_recommendation").$type<{
      quoteId: string;
      vendorId: string;
      quotedCents: number;
      shippingCents: number;
      marginCents: number;
      turnaroundDays?: number;
    }>(),
    fulfillmentSelection: jsonb("fulfillment_selection").$type<{
      vendorId: string;
      quoteId: string;
      isOverride: boolean;
    }>(),
    notes: text("notes"),
    ...timestamps,
  },
  (t) => [
    check(
      "orders_status_check",
      sql`${t.status} IN (${sql.raw(ORDER_STATUSES.map((s) => `'${s}'`).join(", "))})`
    ),
  ]
);

// ---------------------------------------------------------------------------
// order_items
//
// Snapshot fields preserve the purchase record even if the product or its
// options are later edited or deleted.
//
// product_id is nullable: a deleted product does not corrupt order history.
// options_snapshot is jsonb: keeps reads simple and avoids churn as option
// groups evolve. Shape: { [groupName: string]: string }
// ---------------------------------------------------------------------------

export const orderItems = pgTable("order_items", {
  id: uuid("id").primaryKey().defaultRandom(),
  orderId: uuid("order_id")
    .notNull()
    .references(() => orders.id, { onDelete: "cascade" }),
  // Nullable FK — snapshot is source of truth if product is deleted
  productId: uuid("product_id").references(() => products.id, {
    onDelete: "set null",
  }),
  productNameSnapshot: text("product_name_snapshot").notNull(),
  optionsSnapshot: jsonb("options_snapshot")
    .notNull()
    .$type<Record<string, string>>(),
  quantity: integer("quantity").notNull(),
  unitPriceCents: integer("unit_price_cents").notNull(),
  lineTotalCents: integer("line_total_cents").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
    .notNull()
    .defaultNow(),
});

// ---------------------------------------------------------------------------
// order_files
//
// Tracks uploaded artwork per order item.
// Storage content lives in Supabase Storage; only the path is stored here.
// ---------------------------------------------------------------------------

export const ORDER_FILE_STATUSES = [
  "pending_review",
  "approved",
  "rejected",
] as const;

export type OrderFileStatus = (typeof ORDER_FILE_STATUSES)[number];

export const orderFiles = pgTable("order_files", {
  id: uuid("id").primaryKey().defaultRandom(),
  orderItemId: uuid("order_item_id")
    .notNull()
    .references(() => orderItems.id, { onDelete: "cascade" }),
  storagePath: text("storage_path").notNull(),
  originalFilename: text("original_filename").notNull(),
  mimeType: text("mime_type").notNull(),
  sizeBytes: integer("size_bytes").notNull(),
  status: text("status")
    .notNull()
    .default("pending_review")
    .$type<OrderFileStatus>(),
  ...timestamps,
});

// ---------------------------------------------------------------------------
// product_vendor_mappings
//
// Many-to-many: one product can be fulfilled by multiple vendors.
// vendorProductId is the vendor's SKU/product identifier.
// Unique per (product_id, vendor_id) — one mapping per vendor per product.
// ---------------------------------------------------------------------------

export const productVendorMappings = pgTable(
  "product_vendor_mappings",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    productId: uuid("product_id")
      .notNull()
      .references(() => products.id, { onDelete: "cascade" }),
    vendorId: text("vendor_id").notNull(),
    vendorProductId: text("vendor_product_id").notNull(),
    vendorSku: text("vendor_sku"),
    active: boolean("active").notNull().default(true),
    ...timestamps,
  },
  (t) => [
    uniqueIndex("product_vendor_mappings_product_vendor_idx").on(
      t.productId,
      t.vendorId
    ),
  ]
);

// ---------------------------------------------------------------------------
// fulfillment_quotes
//
// One row per vendor quote per order. Multiple vendors may quote the same order.
// rawResponse snapshots the full vendor API response for auditing.
// ---------------------------------------------------------------------------

export const fulfillmentQuotes = pgTable("fulfillment_quotes", {
  id: uuid("id").primaryKey().defaultRandom(),
  orderId: uuid("order_id")
    .notNull()
    .references(() => orders.id, { onDelete: "cascade" }),
  vendorId: text("vendor_id").notNull(),
  quotedCents: integer("quoted_cents").notNull(),
  shippingCents: integer("shipping_cents").notNull().default(0),
  marginCents: integer("margin_cents"),   // order.totalCents − (quotedCents + shippingCents)
  turnaroundDays: integer("turnaround_days"),
  rawResponse: jsonb("raw_response"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
    .notNull()
    .defaultNow(),
});

// ---------------------------------------------------------------------------
// fulfillment_submissions
//
// Tracks the actual API submission to a vendor for a given order.
// vendorOrderId is populated once the vendor accepts the order.
// ---------------------------------------------------------------------------

export const FULFILLMENT_SUBMISSION_STATUSES = [
  "pending",
  "accepted",
  "rejected",
  "cancelled",
] as const;

export type FulfillmentSubmissionStatus =
  (typeof FULFILLMENT_SUBMISSION_STATUSES)[number];

export const fulfillmentSubmissions = pgTable("fulfillment_submissions", {
  id: uuid("id").primaryKey().defaultRandom(),
  orderId: uuid("order_id")
    .notNull()
    .references(() => orders.id, { onDelete: "cascade" }),
  vendorId: text("vendor_id").notNull(),
  vendorOrderId: text("vendor_order_id"),
  status: text("status")
    .notNull()
    .default("pending")
    .$type<FulfillmentSubmissionStatus>(),
  rawRequest: jsonb("raw_request"),
  rawResponse: jsonb("raw_response"),
  ...timestamps,
});

// ---------------------------------------------------------------------------
// fulfillment_events
//
// Inbound webhook payloads from vendors (shipped, tracking_updated, etc.).
// processedAt is null until the event has been handled by our system.
// ---------------------------------------------------------------------------

export const fulfillmentEvents = pgTable("fulfillment_events", {
  id: uuid("id").primaryKey().defaultRandom(),
  orderId: uuid("order_id")
    .notNull()
    .references(() => orders.id, { onDelete: "cascade" }),
  vendorId: text("vendor_id").notNull(),
  eventType: text("event_type").notNull(),
  payload: jsonb("payload").notNull(),
  processedAt: timestamp("processed_at", { withTimezone: true, mode: "date" }),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
    .notNull()
    .defaultNow(),
});

// ---------------------------------------------------------------------------
// preview_sessions
//
// Tracks uploaded images for the Quick Preview flow (/quick-preview).
// Guest users are identified by a server-set cookie token (user_id is nullable).
// TTL: 24 hours — cleaned up by cron or Supabase edge function.
// RLS: access scoped to the sessionToken cookie value (anonymous access).
// ---------------------------------------------------------------------------

export const previewSessions = pgTable("preview_sessions", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id"), // nullable — guest users supported
  sessionToken: text("session_token").notNull().unique(), // server-set cookie for guest RLS
  storagePath: text("storage_path").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
    .notNull()
    .defaultNow(),
});

// ---------------------------------------------------------------------------
// print_specs
//
// Paprintpo-canonical print specs. Stable slugs — never change after creation.
// Read-only for authenticated users; inaccessible to anon (RLS).
// Mirrors the constants in lib/fulfillment/specs.ts; this table is the DB source.
// ---------------------------------------------------------------------------

export const printSpecs = pgTable("print_specs", {
  id: text("id").primaryKey(), // stable slug e.g. "business_card_standard_250"
  productType: text("product_type").notNull(),
  quantity: integer("quantity").notNull(),
  size: text("size").notNull(),
  sides: text("sides").notNull(),
  finish: text("finish").notNull(),
  paperStock: text("paper_stock").notNull(),
  orientation: text("orientation").notNull(),
  bleedMm: integer("bleed_mm").notNull(), // required for vendor submission
  dpiRequired: integer("dpi_required").notNull(), // required for artwork validation
  ...timestamps,
});

// ---------------------------------------------------------------------------
// bundles
//
// DB-driven bundle definitions. Never hardcode bundle contents in code.
// Public read (storefront display). price in cents.
// ---------------------------------------------------------------------------

export const bundles = pgTable("bundles", {
  id: uuid("id").primaryKey().defaultRandom(),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  description: text("description"),
  price: integer("price").notNull(), // cents — may be computed at display time
  active: boolean("active").notNull().default(true),
  ...timestamps,
});

// ---------------------------------------------------------------------------
// bundle_items
//
// Maps a bundle to its canonical print specs.
// quantity_override: null = use the spec's default quantity.
// ---------------------------------------------------------------------------

export const bundleItems = pgTable(
  "bundle_items",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    bundleId: uuid("bundle_id")
      .notNull()
      .references(() => bundles.id, { onDelete: "cascade" }),
    printSpecId: text("print_spec_id")
      .notNull()
      .references(() => printSpecs.id),
    quantityOverride: integer("quantity_override"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("bundle_items_bundle_id_idx").on(t.bundleId),
  ]
);

// ---------------------------------------------------------------------------
// vendor_product_mappings
//
// Maps canonical print specs → vendor SKUs. Server-side only.
// No customer access (RLS denies all non-service-role access).
// Distinct from product_vendor_mappings (which maps product_id → vendor).
// ---------------------------------------------------------------------------

export const vendorProductMappings = pgTable(
  "vendor_product_mappings",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    printSpecId: text("print_spec_id")
      .notNull()
      .references(() => printSpecs.id),
    vendorId: text("vendor_id").notNull(),
    vendorSku: text("vendor_sku").notNull(),
    vendorProductRef: text("vendor_product_ref"),
    active: boolean("active").notNull().default(true),
    ...timestamps,
  },
  (t) => [
    uniqueIndex("vendor_product_mappings_spec_vendor_idx").on(
      t.printSpecId,
      t.vendorId
    ),
  ]
);

// ---------------------------------------------------------------------------
// Inferred row types
// Use these for typed DB reads/writes throughout the app.
// ---------------------------------------------------------------------------

import type { InferSelectModel, InferInsertModel } from "drizzle-orm";

export type Product = InferSelectModel<typeof products>;
export type NewProduct = InferInsertModel<typeof products>;

export type ProductOption = InferSelectModel<typeof productOptions>;
export type NewProductOption = InferInsertModel<typeof productOptions>;

export type QuantityTier = InferSelectModel<typeof quantityTiers>;
export type NewQuantityTier = InferInsertModel<typeof quantityTiers>;

export type Order = InferSelectModel<typeof orders>;
export type NewOrder = InferInsertModel<typeof orders>;

export type OrderItem = InferSelectModel<typeof orderItems>;
export type NewOrderItem = InferInsertModel<typeof orderItems>;

export type OrderFile = InferSelectModel<typeof orderFiles>;
export type NewOrderFile = InferInsertModel<typeof orderFiles>;

export type ProductVendorMapping = InferSelectModel<typeof productVendorMappings>;
export type NewProductVendorMapping = InferInsertModel<typeof productVendorMappings>;

export type FulfillmentQuote = InferSelectModel<typeof fulfillmentQuotes>;
export type NewFulfillmentQuote = InferInsertModel<typeof fulfillmentQuotes>;

export type FulfillmentSubmission = InferSelectModel<typeof fulfillmentSubmissions>;
export type NewFulfillmentSubmission = InferInsertModel<typeof fulfillmentSubmissions>;

export type FulfillmentEvent = InferSelectModel<typeof fulfillmentEvents>;
export type NewFulfillmentEvent = InferInsertModel<typeof fulfillmentEvents>;

export type PreviewSession = InferSelectModel<typeof previewSessions>;
export type NewPreviewSession = InferInsertModel<typeof previewSessions>;

export type PrintSpec = InferSelectModel<typeof printSpecs>;
export type NewPrintSpec = InferInsertModel<typeof printSpecs>;

export type Bundle = InferSelectModel<typeof bundles>;
export type NewBundle = InferInsertModel<typeof bundles>;

export type BundleItem = InferSelectModel<typeof bundleItems>;
export type NewBundleItem = InferInsertModel<typeof bundleItems>;

export type VendorProductMapping = InferSelectModel<typeof vendorProductMappings>;
export type NewVendorProductMapping = InferInsertModel<typeof vendorProductMappings>;
