// Drizzle schema — Phase 2
// Tables: products, product_options, quantity_tiers, orders, order_items, order_files
//
// Conventions:
//   - All monetary values are in cents (integer) — no floats.
//   - Timestamps are timestamptz stored as JS Date objects.
//   - UUIDs are generated by Postgres (gen_random_uuid()).
//   - Order status is plain text + check constraint (not a PG enum) so adding
//     a new status value never requires a migration.

import {
  pgTable,
  uuid,
  text,
  integer,
  boolean,
  jsonb,
  timestamp,
  uniqueIndex,
  check,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" })
    .notNull()
    .defaultNow(),
};

// ---------------------------------------------------------------------------
// products
// ---------------------------------------------------------------------------

export const products = pgTable("products", {
  id: uuid("id").primaryKey().defaultRandom(),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  description: text("description"),
  category: text("category").notNull(),
  basePrice: integer("base_price").notNull(), // cents
  active: boolean("active").notNull().default(true),
  ...timestamps,
});

// ---------------------------------------------------------------------------
// product_options
//
// One row per selectable option value (not per option group).
// group_name is the logical grouping key: "size", "finish", "material", etc.
// Unique per (product_id, group_name, value) — no duplicate values within a group.
// ---------------------------------------------------------------------------

export const productOptions = pgTable(
  "product_options",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    productId: uuid("product_id")
      .notNull()
      .references(() => products.id, { onDelete: "cascade" }),
    groupName: text("group_name").notNull(),
    label: text("label").notNull(),
    value: text("value").notNull(),
    priceModifier: integer("price_modifier").notNull().default(0), // cents delta
    sortOrder: integer("sort_order").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("product_options_product_group_value_idx").on(
      t.productId,
      t.groupName,
      t.value
    ),
  ]
);

// ---------------------------------------------------------------------------
// quantity_tiers
//
// Each tier: buy at least min_qty units → pay unit_price cents each.
// Highest qualifying tier (largest min_qty ≤ selected qty) wins.
// See lib/pricing.ts for resolution logic.
// ---------------------------------------------------------------------------

export const quantityTiers = pgTable(
  "quantity_tiers",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    productId: uuid("product_id")
      .notNull()
      .references(() => products.id, { onDelete: "cascade" }),
    minQty: integer("min_qty").notNull(),
    unitPrice: integer("unit_price").notNull(), // cents per unit at this tier
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("quantity_tiers_product_min_qty_idx").on(
      t.productId,
      t.minQty
    ),
  ]
);

// ---------------------------------------------------------------------------
// orders
//
// No user_id FK yet — Supabase auth is Phase 4.
// customer_email is the placeholder link to future accounts.
//
// status values (check constraint keeps them without a PG enum):
//   pending → paid → artwork_review → proof_sent → proof_approved
//   → in_production → shipped → complete
//   + terminal: payment_failed, cancelled
// ---------------------------------------------------------------------------

export const ORDER_STATUSES = [
  "pending",
  "paid",
  "artwork_review",
  "proof_sent",
  "proof_approved",
  "in_production",
  "shipped",
  "complete",
  "payment_failed",
  "cancelled",
] as const;

export type OrderStatus = (typeof ORDER_STATUSES)[number];

export const orders = pgTable(
  "orders",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    customerEmail: text("customer_email").notNull(),
    customerName: text("customer_name").notNull(),
    status: text("status")
      .notNull()
      .default("pending")
      .$type<OrderStatus>(),
    stripeSessionId: text("stripe_session_id"),
    stripePaymentIntent: text("stripe_payment_intent"),
    subtotalCents: integer("subtotal_cents").notNull(), // sum of line totals before any fees/tax
    totalCents: integer("total_cents").notNull(),       // final charged amount
    notes: text("notes"),
    ...timestamps,
  },
  (t) => [
    check(
      "orders_status_check",
      sql`${t.status} IN (${sql.raw(ORDER_STATUSES.map((s) => `'${s}'`).join(", "))})`
    ),
  ]
);

// ---------------------------------------------------------------------------
// order_items
//
// Snapshot fields preserve the purchase record even if the product or its
// options are later edited or deleted.
//
// product_id is nullable: a deleted product does not corrupt order history.
// options_snapshot is jsonb: keeps reads simple and avoids churn as option
// groups evolve. Shape: { [groupName: string]: string }
// ---------------------------------------------------------------------------

export const orderItems = pgTable("order_items", {
  id: uuid("id").primaryKey().defaultRandom(),
  orderId: uuid("order_id")
    .notNull()
    .references(() => orders.id, { onDelete: "cascade" }),
  // Nullable FK — snapshot is source of truth if product is deleted
  productId: uuid("product_id").references(() => products.id, {
    onDelete: "set null",
  }),
  productNameSnapshot: text("product_name_snapshot").notNull(),
  optionsSnapshot: jsonb("options_snapshot")
    .notNull()
    .$type<Record<string, string>>(),
  quantity: integer("quantity").notNull(),
  unitPriceCents: integer("unit_price_cents").notNull(),
  lineTotalCents: integer("line_total_cents").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
    .notNull()
    .defaultNow(),
});

// ---------------------------------------------------------------------------
// order_files
//
// Tracks uploaded artwork per order item.
// Storage content lives in Supabase Storage; only the path is stored here.
// ---------------------------------------------------------------------------

export const ORDER_FILE_STATUSES = [
  "pending_review",
  "approved",
  "rejected",
] as const;

export type OrderFileStatus = (typeof ORDER_FILE_STATUSES)[number];

export const orderFiles = pgTable("order_files", {
  id: uuid("id").primaryKey().defaultRandom(),
  orderItemId: uuid("order_item_id")
    .notNull()
    .references(() => orderItems.id, { onDelete: "cascade" }),
  storagePath: text("storage_path").notNull(),
  originalFilename: text("original_filename").notNull(),
  mimeType: text("mime_type").notNull(),
  sizeBytes: integer("size_bytes").notNull(),
  status: text("status")
    .notNull()
    .default("pending_review")
    .$type<OrderFileStatus>(),
  ...timestamps,
});

// ---------------------------------------------------------------------------
// Inferred row types
// Use these for typed DB reads/writes throughout the app.
// ---------------------------------------------------------------------------

import type { InferSelectModel, InferInsertModel } from "drizzle-orm";

export type Product = InferSelectModel<typeof products>;
export type NewProduct = InferInsertModel<typeof products>;

export type ProductOption = InferSelectModel<typeof productOptions>;
export type NewProductOption = InferInsertModel<typeof productOptions>;

export type QuantityTier = InferSelectModel<typeof quantityTiers>;
export type NewQuantityTier = InferInsertModel<typeof quantityTiers>;

export type Order = InferSelectModel<typeof orders>;
export type NewOrder = InferInsertModel<typeof orders>;

export type OrderItem = InferSelectModel<typeof orderItems>;
export type NewOrderItem = InferInsertModel<typeof orderItems>;

export type OrderFile = InferSelectModel<typeof orderFiles>;
export type NewOrderFile = InferInsertModel<typeof orderFiles>;
